import argparse
from .sender import send_file
from .receiver import receive_file
from .discover import discover_transfers

def main():
    parser = argparse.ArgumentParser(
        description="LAN Transfer CLI - Ultra-fast and robust tool to transfer files between local PCs.",
        epilog="Examples:\n"
               "  Send:    lan-transfer send \"C:\\Path\\To\\Video.mp4\" --users 3\n"
               "  Receive: lan-transfer receive 192.168.1.5:54321 Video.mp4 --pin 1234 --key A8X2...\n"
               "  Radar:   lan-transfer discover",
        formatter_class=argparse.RawTextHelpFormatter
    )
    
    subparsers = parser.add_subparsers(dest="command", help="Operation commands")
    
    # Sub-parser for Sending
    send_parser = subparsers.add_parser("send", help="Opens a temporary server and exposes the specified file/folder for download.")
    send_parser.add_argument("filepath", type=str, help="Absolute or relative path of the file or folder to send.")
    send_parser.add_argument("--users", type=int, default=1, help="Number of successful downloads allowed before closing (default: 1).")
    
    # Sub-parser for Receiving
    receive_parser = subparsers.add_parser("receive", help="Connects to a local sender and downloads a file showing progress.")
    receive_parser.add_argument("address", type=str, help="IP and Port of the sender (e.g. 192.168.1.5:8080).")
    receive_parser.add_argument("filename", type=str, help="The encoded filename given by the sender command.")
    receive_parser.add_argument("--pin", type=str, required=True, help="4-digit security PIN.")
    receive_parser.add_argument("--key", type=str, required=True, help="AES-256 key generated by the sender.")
    
    # Sub-parser for Discover
    discover_parser = subparsers.add_parser("discover", help="Scans the local network for available LAN Transfers.")
    
    args = parser.parse_args()
    
    if args.command == "send":
        send_file(args.filepath, users=args.users)
    elif args.command == "receive":
        receive_file(args.address, args.filename, args.pin, args.key)
    elif args.command == "discover":
        discover_transfers()
    else:
        # If no command passed, show help
        parser.print_help()

if __name__ == "__main__":
    main()
